# Generated by Django 4.0.3 on 2022-03-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0003_geeksmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
