# Generated by Django 4.0.3 on 2022-03-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0004_delete_geeksmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='advertiser_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
