# Generated by Django 4.0.3 on 2022-03-06 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0006_alter_ad_advertiser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='advertiser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.advertiser'),
        ),
    ]
