# Generated by Django 4.0.3 on 2022-03-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0010_remove_ad_image_url_ad_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='advertiser_id',
            new_name='advertiser',
        ),
    ]
