# Generated by Django 4.0.3 on 2022-03-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0013_profile_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
