# Generated by Django 4.0.3 on 2022-03-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0016_rename_clicked_date_clicks_created_alter_ad_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='views',
            old_name='viewed_date',
            new_name='created',
        ),
    ]
