# Generated by Django 4.0.3 on 2022-03-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0017_rename_viewed_date_views_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicks',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='views',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
