# Generated by Django 4.0.3 on 2022-03-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0018_alter_clicks_created_alter_views_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicks',
            name='user_ip',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='views',
            name='user_ip',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
