# Generated by Django 4.0.3 on 2022-03-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0019_alter_clicks_user_ip_alter_views_user_ip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clicks',
            new_name='Click',
        ),
    ]
