# Generated by Django 4.0.3 on 2022-03-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0020_rename_clicks_click'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Views',
            new_name='View',
        ),
    ]
