# Generated by Django 4.0.3 on 2022-03-13 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0021_rename_views_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clicks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clicked_date', models.DateTimeField()),
                ('user_ip', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('viewed_date', models.DateTimeField()),
                ('user_ip', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='view',
            name='ad',
        ),
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='ad',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Click',
        ),
        migrations.DeleteModel(
            name='View',
        ),
        migrations.AddField(
            model_name='views',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.ad'),
        ),
        migrations.AddField(
            model_name='clicks',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.ad'),
        ),
    ]
