# Generated by Django 4.0.3 on 2022-03-13 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0022_clicks_views_remove_view_ad_alter_ad_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_ip', models.GenericIPAddressField(protocol='IPv4')),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_ip', models.GenericIPAddressField(protocol='IPv4')),
            ],
        ),
        migrations.RemoveField(
            model_name='views',
            name='ad',
        ),
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(upload_to='ads_images'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Clicks',
        ),
        migrations.DeleteModel(
            name='Views',
        ),
        migrations.AddField(
            model_name='view',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.ad'),
        ),
        migrations.AddField(
            model_name='click',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.ad'),
        ),
    ]
