# Generated by Django 4.0.3 on 2022-03-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0005_ad_advertiser_id_alter_ad_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='advertiser_id',
            field=models.PositiveIntegerField(),
        ),
    ]
