# Generated by Django 4.0.3 on 2022-03-06 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0011_rename_advertiser_id_ad_advertiser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='views',
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('viewed_date', models.DateTimeField()),
                ('user_ip', models.CharField(max_length=15)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Clicks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clicked_date', models.DateTimeField()),
                ('user_ip', models.CharField(max_length=15)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.ad')),
            ],
        ),
    ]
