# Generated by Django 4.0.3 on 2022-03-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0015_alter_ad_advertiser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('views_count', models.PositiveIntegerField()),
                ('clicks_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HourlyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('views_count', models.PositiveIntegerField()),
                ('clicks_count', models.PositiveIntegerField()),
            ],
        ),
    ]
